// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehfhstaqadbfrhfuxius.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZmhzdGFxYWRiZnJoZnV4aXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzk2MTEsImV4cCI6MjA2MzY1NTYxMX0.XBQJyqNuJQrESovR0qqGwAD5u6N1QDJYvhX-qt4k3lo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});